"""research — trust tooling: walk-forward (+ purge/embargo), Deflated Sharpe, look-ahead linter, Optuna optimize, tearsheet, Run Library (§11, §17)."""

from __future__ import annotations

from .deflated import (
    DeflatedSharpe,
    deflated_sharpe,
    expected_max_sharpe,
    kurtosis,
    probabilistic_sharpe,
    skewness,
    trial_sharpes,
)
from .lookahead import (
    BLIND_SPOTS,
    DEGENERATE_LABEL_HORIZON,
    FUTURE_INDEX,
    FUTURE_SHIFT,
    TRUNCATION_DIVERGENCE,
    UNBOUNDED_AGGREGATE,
    UNIVERSE_LOOKAHEAD,
    LeakFinding,
    LookaheadResult,
    analyze,
    check_label_horizon,
    lint_source,
    truncation_probe,
)
from .funding_lab import (
    HOURS_PER_YEAR_365,
    BasisPoint,
    DislocationPoint,
    DislocationSeries,
    VenueFundingStat,
    annualize_hourly,
    annualized_rate,
    basis_series,
    cross_venue_dislocation,
    mean_basis_bps,
    settlements_per_day,
    settlements_per_year,
    venue_funding_stats,
)
from .tearsheet import (
    MetricSummary,
    PerformanceReport,
    annualization_factor,
    bar_returns,
    bars_per_year,
    build_report,
    downside_deviation,
    equity_points_from_events,
    equity_series_from_events,
    max_drawdown,
    sharpe,
    sortino,
    summarize_equity,
    win_rate_from_events,
)
from .runlib import (
    BUNDLE_VERSION,
    DIFFERENT_ENGINE_WARNING,
    DIFFERENT_LAKE_WARNING,
    DIFFERENT_RANGE_WARNING,
    BundleRunner,
    DataSource,
    ReproBundle,
    ReproductionResult,
    RunComparison,
    RunManifest,
    compare,
    content_hash,
    engine_version,
    export_bundle,
    import_legacy_runs,
    legacy_run_manifests,
    list_runs,
    load_run,
    persist_run,
    reproduce,
)
from .walkforward import (
    BacktestRunner,
    ParamSpace,
    WalkForwardConfig,
    WalkForwardResult,
    WalkForwardWarning,
    Window,
    WindowResult,
    plan_windows,
    run_walk_forward,
)

__all__ = [
    # walk-forward + optimizer (6.1)
    "BacktestRunner",
    "ParamSpace",
    "WalkForwardConfig",
    "WalkForwardResult",
    "WalkForwardWarning",
    "Window",
    "WindowResult",
    "plan_windows",
    "run_walk_forward",
    # look-ahead / leakage linter (6.3, §8.5/§11/D27)
    "analyze",
    "lint_source",
    "truncation_probe",
    "check_label_horizon",
    "LeakFinding",
    "LookaheadResult",
    "BLIND_SPOTS",
    "FUTURE_SHIFT",
    "FUTURE_INDEX",
    "UNBOUNDED_AGGREGATE",
    "DEGENERATE_LABEL_HORIZON",
    "UNIVERSE_LOOKAHEAD",
    "TRUNCATION_DIVERGENCE",
    # metrics + performance report (6.2, §11.1)
    "MetricSummary",
    "PerformanceReport",
    "annualization_factor",
    "bar_returns",
    "bars_per_year",
    "build_report",
    "downside_deviation",
    "max_drawdown",
    "sharpe",
    "sortino",
    "summarize_equity",
    "win_rate_from_events",
    "equity_series_from_events",
    "equity_points_from_events",
    # funding/basis lab (6.5, §10/D28)
    "HOURS_PER_YEAR_365",
    "settlements_per_day",
    "settlements_per_year",
    "annualize_hourly",
    "annualized_rate",
    "VenueFundingStat",
    "venue_funding_stats",
    "DislocationPoint",
    "DislocationSeries",
    "cross_venue_dislocation",
    "BasisPoint",
    "basis_series",
    "mean_basis_bps",
    # deflated sharpe (6.2, D22)
    "DeflatedSharpe",
    "deflated_sharpe",
    "expected_max_sharpe",
    "kurtosis",
    "probabilistic_sharpe",
    "skewness",
    "trial_sharpes",
    # run library + reproducibility export (6.4, §11.2/§2.10)
    "RunManifest",
    "DataSource",
    "RunComparison",
    "ReproBundle",
    "ReproductionResult",
    "BundleRunner",
    "persist_run",
    "load_run",
    "list_runs",
    "compare",
    "export_bundle",
    "reproduce",
    "content_hash",
    "engine_version",
    "legacy_run_manifests",
    "import_legacy_runs",
    "BUNDLE_VERSION",
    "DIFFERENT_RANGE_WARNING",
    "DIFFERENT_ENGINE_WARNING",
    "DIFFERENT_LAKE_WARNING",
]
