"""research — trust tooling: walk-forward (+ purge/embargo), Deflated Sharpe, look-ahead linter, Optuna optimize, tearsheet, Run Library (§11, §17)."""

from __future__ import annotations

from .deflated import (
    DeflatedSharpe,
    deflated_sharpe,
    expected_max_sharpe,
    kurtosis,
    probabilistic_sharpe,
    skewness,
    trial_sharpes,
)
from .lookahead import (
    BLIND_SPOTS,
    DEGENERATE_LABEL_HORIZON,
    FUTURE_INDEX,
    FUTURE_SHIFT,
    TRUNCATION_DIVERGENCE,
    UNBOUNDED_AGGREGATE,
    UNIVERSE_LOOKAHEAD,
    LeakFinding,
    LookaheadResult,
    analyze,
    check_label_horizon,
    lint_source,
    truncation_probe,
)
from .tearsheet import (
    MetricSummary,
    PerformanceReport,
    annualization_factor,
    bar_returns,
    bars_per_year,
    build_report,
    downside_deviation,
    max_drawdown,
    sharpe,
    sortino,
    summarize_equity,
    win_rate_from_events,
)
from .walkforward import (
    BacktestRunner,
    ParamSpace,
    WalkForwardConfig,
    WalkForwardResult,
    WalkForwardWarning,
    Window,
    WindowResult,
    plan_windows,
    run_walk_forward,
)

__all__ = [
    # walk-forward + optimizer (6.1)
    "BacktestRunner",
    "ParamSpace",
    "WalkForwardConfig",
    "WalkForwardResult",
    "WalkForwardWarning",
    "Window",
    "WindowResult",
    "plan_windows",
    "run_walk_forward",
    # look-ahead / leakage linter (6.3, §8.5/§11/D27)
    "analyze",
    "lint_source",
    "truncation_probe",
    "check_label_horizon",
    "LeakFinding",
    "LookaheadResult",
    "BLIND_SPOTS",
    "FUTURE_SHIFT",
    "FUTURE_INDEX",
    "UNBOUNDED_AGGREGATE",
    "DEGENERATE_LABEL_HORIZON",
    "UNIVERSE_LOOKAHEAD",
    "TRUNCATION_DIVERGENCE",
    # metrics + performance report (6.2, §11.1)
    "MetricSummary",
    "PerformanceReport",
    "annualization_factor",
    "bar_returns",
    "bars_per_year",
    "build_report",
    "downside_deviation",
    "max_drawdown",
    "sharpe",
    "sortino",
    "summarize_equity",
    "win_rate_from_events",
    # deflated sharpe (6.2, D22)
    "DeflatedSharpe",
    "deflated_sharpe",
    "expected_max_sharpe",
    "kurtosis",
    "probabilistic_sharpe",
    "skewness",
    "trial_sharpes",
]
