#!/usr/bin/env python
"""Auto-update count markers in README.md — Phase 4 T4.1.

Computes live counts from the codebase and injects them into README.md
between `<!-- counts:auto -->` / `<!-- /counts:auto -->` markers. Idempotent:
running multiple times only changes the file when a count has moved.

Usage:
    python scripts/update_readme_counts.py            # rewrite
    python scripts/update_readme_counts.py --check    # CI mode: exit 1 on drift

CI (Phase 5.5) runs `--check` on every push so README can't go stale.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
README = ROOT / "README.md"

START = "<!-- counts:auto -->"
END = "<!-- /counts:auto -->"


def _count_strategies() -> int:
    """User-facing strategy .py files under flint/strategy/, minus infra."""
    d = ROOT / "flint" / "strategy"
    infra = {"__init__", "base", "loader"}
    return sum(
        1 for p in d.glob("*.py")
        if p.stem not in infra and not p.stem.startswith("_")
    )


def _count_tests() -> int:
    """Sum of `def test_` occurrences across tests/."""
    n = 0
    for p in (ROOT / "tests").rglob("test_*.py"):
        text = p.read_text(encoding="utf-8", errors="ignore")
        n += sum(1 for line in text.splitlines()
                 if line.lstrip().startswith("def test_"))
    return n


def _count_endpoints() -> int:
    """Every `@router.(get|post|put|delete|patch)(...)` + top-level `@app.(get|post|...)` in api/."""
    n = 0
    methods = ("get", "post", "put", "delete", "patch")
    api_dir = ROOT / "flint" / "api"
    for p in api_dir.rglob("*.py"):
        text = p.read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            s = line.strip()
            for m in methods:
                if s.startswith(f"@router.{m}(") or s.startswith(f"@app.{m}("):
                    n += 1
                    break
    return n


def _count_mcp_tools() -> int:
    p = ROOT / "flint" / "mcp_server.py"
    if not p.exists():
        return 0
    text = p.read_text(encoding="utf-8", errors="ignore")
    return sum(1 for line in text.splitlines()
               if line.strip().startswith("@mcp.tool()"))


def _count_providers() -> int:
    """Provider modules under flint/providers/ minus infra."""
    d = ROOT / "flint" / "providers"
    infra = {"__init__", "base", "registry", "websocket"}
    return sum(
        1 for p in d.glob("*.py")
        if p.stem not in infra and not p.stem.startswith("_")
    )


def build_block() -> str:
    n_strats = _count_strategies()
    n_tests = _count_tests()
    n_endpoints = _count_endpoints()
    n_mcp = _count_mcp_tools()
    n_providers = _count_providers()
    lines = [
        START,
        f"- **{n_strats} built-in strategies** · **{n_providers} data providers** · "
        f"**{n_endpoints} REST endpoints** · **{n_mcp} MCP tools** · **{n_tests} tests**",
        "",
        "_Counts auto-generated by `scripts/update_readme_counts.py`._",
        END,
    ]
    return "\n".join(lines)


def rewrite(dry_run: bool = False) -> bool:
    """Returns True if README changed (or would change in dry-run)."""
    text = README.read_text(encoding="utf-8")
    block = build_block()

    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END),
        re.DOTALL,
    )
    if pattern.search(text):
        new_text = pattern.sub(block, text)
    else:
        # First-run: insert after the first `---` separator (end of hero).
        separator = "\n---\n"
        if separator not in text:
            raise SystemExit(
                "README.md is missing the hero-section '---' separator; "
                "cannot place auto-counts block."
            )
        before, after = text.split(separator, 1)
        new_text = f"{before}{separator}\n{block}\n{separator}{after}"

    changed = new_text != text
    if changed and not dry_run:
        README.write_text(new_text, encoding="utf-8")
    return changed


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="Don't write; exit 1 if README is stale")
    args = parser.parse_args()
    changed = rewrite(dry_run=args.check)
    if args.check and changed:
        print("README count block is stale — run scripts/update_readme_counts.py",
              file=sys.stderr)
        sys.exit(1)
    if changed:
        print(f"Updated {README}")
    else:
        print(f"{README} already up to date")


if __name__ == "__main__":
    main()
